name: Windows Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Rust App on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Build Release Binary
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pinwheel-windows
          path: target/x86_64-pc-windows-msvc/release/pinwheel.exe
          retention-days: 7
